---
title: "11-Load-Individual-Puncta-Data"
output: html_notebook
---

Input CSV file and filling in rows
*change input file name*
*change BvsS type*
*change replicate #*

```{r}
testdata=read.csv(file="~/Desktop/eqNum-results_LAMP-PCC_1Jul20/15Mar20_eqCellSum-PCC_basal_1Jul20.csv",header=TRUE)
testdata$BvsS<-"Basal"
testdata$Rep<-3
nobs=nrow(testdata)
for (i in 1:nobs) {
  if (is.na(testdata[i,3])) {
    testdata[i,1]<-fname
    testdata[i,2]<-LC3TotVol
    testdata[i,3]<-LC3puncta
    testdata[i,4]<-LC3mInt
    testdata[i,5]<-Nuc
    testdata[i,6]<-LAMPmInt
    testdata[i,7]<-LAMPstInt
    testdata[i,8]<-LAMPTotVol
  } 
  else {
    fname=testdata[i,1]
    LC3TotVol=testdata[i,2]
    LC3puncta=testdata[i,3]
    LC3mInt=testdata[i,4]
    Nuc=testdata[i,5]
    LAMPmInt=testdata[i,6]
    LAMPstInt=testdata[i,7]
    LAMPTotVol=testdata[i,8]
  }
}

testdata2=read.csv(file="~/Desktop/eqNum-results_LAMP-PCC_1Jul20/15Mar20_eqCellSum-PCC_starved_1Jul20.csv",header=TRUE)
testdata2$BvsS<-"Starved"
testdata2$Rep<-3
nobs=nrow(testdata2)
for (i in 1:nobs) {
  if (is.na(testdata2[i,3])) {
    testdata2[i,1]<-fname
    testdata2[i,2]<-LC3TotVol
    testdata2[i,3]<-LC3puncta
    testdata2[i,4]<-LC3mInt
    testdata2[i,5]<-Nuc
    testdata2[i,6]<-LAMPmInt
    testdata2[i,7]<-LAMPstInt
    testdata2[i,8]<-LAMPTotVol
  } 
  else {
    fname=testdata2[i,1]
    LC3TotVol=testdata2[i,2]
    LC3puncta=testdata2[i,3]
    LC3mInt=testdata2[i,4]
    Nuc=testdata2[i,5]
    LAMPmInt=testdata2[i,6]
    LAMPstInt=testdata2[i,7]
    LAMPTotVol=testdata2[i,8]
  }
}
temp<-rbind(testdata,testdata2)
```

Adding type designation
*if necessary update substring values based on filename in input document*

```{r}
temp$Type<-NA
ntemp<-nrow(temp)


for (c in 1:ntemp) {
  if (substr(temp[c,1],47,47)=="W") {
    temp$Type[c]<-"WT"
  }
 # else if (substr(temp[c,1],47,47)=="M") {
#    temp$Type[c]<-"Mock"
 # }
  else if (substr(temp[c,1],47,47)=="C") {
    temp$Type[c]<-"Control"
  }
  else if (substr(temp[c,1],47,47)=="t") {
    temp$Type[c]<-"tepsin"
  }
  else {
    temp$Type[c]<-"AP4E1"
  }
  
}
temp$Type<-factor(temp$Type, levels=c("WT", "Mock", "Control", "tepsin", "AP4E1"))
```

Calculating Summary Statistics
```{r}
temp$IndeVolVar<-NA
temp$IndeVolMean<-NA
temp$IndeVolSTD<-NA
temp$IndeVolMed<-NA

temp$BvsS<-factor(temp$BvsS, levels=c("Basal", "Starved"))

for (t in c("WT","Mock", "Control", "tepsin", "AP4E1")) {
  for (bs in c("Basal", "Starved")) {
  temp$IndeVolMean[which(temp$Type==t & temp$BvsS==bs)]<-mean(temp$LC3Volume[which(temp$Type==t & temp$BvsS==bs)],na.rm = T)
   
  temp$IndeVolMed[which(temp$Type==t & temp$BvsS==bs)]<-median(temp$LC3Volume[which(temp$Type==t & temp$BvsS==bs)],na.rm = T)
  
  temp$IndeVolVar[which(temp$Type==t & temp$BvsS==bs)]<-var(temp$LC3Volume[which(temp$Type==t & temp$BvsS==bs)],na.rm = T)
  
  temp$IndeVolSTD[which(temp$Type==t & temp$BvsS==bs)]<-sd(temp$LC3Volume[which(temp$Type==t & temp$BvsS==bs)],na.rm = T)
 
   }
}
```


calculating number of enlarged puncta

```{r}
temp$EnlargedPunctaCount<-NA

temp$BvsS<-factor(temp$BvsS, levels=c("Basal", "Starved"))

for (t in c("WT","Mock", "Control", "tepsin", "AP4E1")) {
  for (bs in c("Basal", "Starved")) {
    temp$EnlargedPunctaCount[which(temp$Type==t & temp$BvsS==bs)]<-length(which(temp$Type==t & temp$BvsS==bs & temp$LC3Volume >2 & temp$Type==t & temp$BvsS==bs & temp$LC3Volume < 10))
  }
}
```
