---
title: "12-Load-PrelimNucleiCount-dataset"
output: html_notebook
---

Load dataframe
*change input file*
*change replicate #*
```{r}
testdata=read.csv(file="~/Desktop/analysis_20Aug20/nuclei-counts/NSW3003_cell-count_basal_27Aug20.csv",header=TRUE)
testdata$BvsS<-"Basal"
testdata$Rep<-2

testdata2=read.csv(file="~/Desktop/analysis_20Aug20/nuclei-counts/NSW3003_cell-count_starved_27Aug20.csv",header=TRUE)
testdata2$BvsS<-"Starved"
testdata2$Rep<-2

temp<-rbind(testdata,testdata2)
```

Adding type designation
*if necessary update substring values based on filename in input document*
```{r}
temp$Type<-NA
ntemp<-nrow(temp)


for (c in 1:ntemp) {
  if (substr(temp[c,1],35,35)=="W") {
    temp$Type[c]<-"WT"
  }
  else if (substr(temp[c,1],35,35)=="M") {
    temp$Type[c]<-"Mock"
  }
  else if (substr(temp[c,1],35,35)=="C") {
    temp$Type[c]<-"Control"
  }
  else if (substr(temp[c,1],35,35)=="t") {
    temp$Type[c]<-"tepsin"
  }
  else {
    temp$Type[c]<-"AP4E1"
  }
  
}
temp$Type<-factor(temp$Type, levels=c("WT", "Mock", "Control", "tepsin", "AP4E1"))
```

Get Sum of cell counts per type
```{r}
temp$CellSum<-NA

for (t in c("WT","Mock", "Control", "tepsin", "AP4E1")) {
  for (bs in c("Basal", "Starved")) {
  temp$CellSum[which(temp$Type==t & temp$BvsS==bs)]<-sum(temp$NucleiCount[which(temp$Type==t & temp$BvsS==bs)])
   }
}
```

