---
title: "13-Load-Western-quantification"
output: html_notebook
---

CSV import - Mac
*change input file path*
```{r}
WBdata=read.csv(file="~/Desktop/analysis_20Aug20/WB-quant/15Mar-NSW3001-NSW3005_quant-results_17Sep20.csv",header=TRUE)

```

CSV import - Windows
*change input file path*
```{r}
WBdata=read.csv(file="./Analysis-files/WB-Analysis/NSW3010-12-16_WB-compiled_12Mar21.csv",header=TRUE)

```


Calculate mean for each condition
```{r}
WBdata$LC3ratioAve<-NA
WBdata$LC3ratioNormAve<-NA
WBdata$LC3IIAve<-NA
WBdata$tepsinKDAve<-NA
WBdata$AP4EKDAve<-NA

for (t in c("WT", "Control", "tepsin", "AP4E1")) {
  for (bs in c("Basal", "Starved")) {
  WBdata$LC3ratioAve[which(WBdata$type==t & WBdata$BvsS==bs)]<-sum(WBdata$LC3ratio[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3ratio)])/length(which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3ratio))
  
  WBdata$LC3ratioNormAve[which(WBdata$type==t & WBdata$BvsS==bs)]<-sum(WBdata$LC3ratioNorm[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3ratioNorm)])/length(which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3ratioNorm))
  
   WBdata$LC3IIAve[which(WBdata$type==t & WBdata$BvsS==bs)]<-sum(WBdata$LC3II[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3II)])/length(which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3II))
 
  WBdata$tepsinKDAve[which(WBdata$type==t & WBdata$BvsS==bs)]<-sum(WBdata$tepsinKD[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$tepsinKD)])/length(which(WBdata$type==t & WBdata$BvsS==bs & WBdata$tepsinKD))
  
  WBdata$AP4EKDAve[which(WBdata$type==t & WBdata$BvsS==bs)]<-sum(WBdata$AP4EKD[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$AP4EKD)])/length(which(WBdata$type==t & WBdata$BvsS==bs & WBdata$AP4EKD))
  
   }
}


```

Calculate standard deviation for each condition
```{r}
WBdata$LC3ratioSD<-NA
WBdata$LC3ratioNormSD<-NA
WBdata$LC3IISD<-NA
WBdata$tepsinKDSD<-NA
WBdata$AP4EKDSD<-NA

for (t in c("WT", "Control", "tepsin", "AP4E1")) {
  for (bs in c("Basal", "Starved")) {
  WBdata$LC3ratioSD[which(WBdata$type==t & WBdata$BvsS==bs)]<-sd(WBdata$LC3ratio[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3ratio)])
 
  WBdata$LC3ratioNormSD[which(WBdata$type==t & WBdata$BvsS==bs)]<-sd(WBdata$LC3ratioNorm[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3ratioNorm)])
  
  WBdata$LC3IISD[which(WBdata$type==t & WBdata$BvsS==bs)]<-sd(WBdata$LC3II[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3II)])
  
  WBdata$tepsinKDSD[which(WBdata$type==t & WBdata$BvsS==bs)]<-sd(WBdata$tepsinKD[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$tepsinKD)])
  
  WBdata$AP4EKDSD[which(WBdata$type==t & WBdata$BvsS==bs)]<-sd(WBdata$AP4EKD[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$AP4EKD)])
  
   }
}
```

Calculate standard error for each condition
```{r}
WBdata$LC3ratioSE<-NA
WBdata$LC3ratioNormSE<-NA
WBdata$LC3IISE<-NA
WBdata$tepsinKDSE<-NA
WBdata$AP4EKDSE<-NA

for (t in c("WT", "Control", "tepsin", "AP4E1")) {
  for (bs in c("Basal", "Starved")) {
  WBdata$LC3ratioSE[which(WBdata$type==t & WBdata$BvsS==bs)]<-sd(WBdata$LC3ratio[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3ratio)])/sqrt(length(which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3ratio)))
 
  WBdata$LC3ratioNormSE[which(WBdata$type==t & WBdata$BvsS==bs)]<-sd(WBdata$LC3ratioNorm[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3ratioNorm)])/sqrt(length(which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3ratioNorm)))
  
  WBdata$LC3IISE[which(WBdata$type==t & WBdata$BvsS==bs)]<-sd(WBdata$LC3II[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3II)])/sqrt(length(which(WBdata$type==t & WBdata$BvsS==bs & WBdata$LC3II)))
  
  WBdata$tepsinKDSE[which(WBdata$type==t & WBdata$BvsS==bs)]<-sd(WBdata$tepsinKD[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$tepsinKD)])/sqrt(length(which(WBdata$type==t & WBdata$BvsS==bs & WBdata$tepsinKD)))
  
  WBdata$AP4EKDSE[which(WBdata$type==t & WBdata$BvsS==bs)]<-sd(WBdata$AP4EKD[which(WBdata$type==t & WBdata$BvsS==bs & WBdata$AP4EKD)])/sqrt(length(which(WBdata$type==t & WBdata$BvsS==bs & WBdata$AP4EKD)))
  
   }
}
```


Remove duplicate rows from replicates
```{r}
WBdata_nodup<-WBdata[!duplicated(WBdata$LC3ratioAve),]
```




