---
title: "14-Load-Total-Puncta-Count-Data"
output: html_notebook
---

CSV import
*change input file path*
```{r}
Countdata=read.csv(file="~/Desktop/analysis_20Aug20/LC3-LAMP_analysis/cleaned_9Sep20/Calculated-PercEnlarged-AveVolEnlarged_17Sep20.csv",header=TRUE)

```

To remove a replicate
*only use to remove data*
```{r}
Countdata$replicate<-factor(Countdata$replicate, levels=c("1", "2","3"))
Countdata<-Countdata[which(Countdata$replicate!="1"),]
```


Calculate mean for each condition
```{r}
Countdata$PunctaTotAve<-NA
Countdata$LC3EnlargedAve<-NA
Countdata$PercEnlargedAve<-NA
Countdata$AveVolEnlargedAve<-NA


for (t in c("WT", "Control", "tepsin", "AP4E1")) {
  for (bs in c("Basal", "Starved")) {
  Countdata$PunctaTotAve[which(Countdata$type==t & Countdata$BvsS==bs)]<-sum(Countdata$PunctaTot[which(Countdata$type==t & Countdata$BvsS==bs & Countdata$PunctaTot)])/length(which(Countdata$type==t & Countdata$BvsS==bs & Countdata$PunctaTot))
  
  Countdata$LC3EnlargedAve[which(Countdata$type==t & Countdata$BvsS==bs)]<-sum(Countdata$LC3Enlarged[which(Countdata$type==t & Countdata$BvsS==bs & Countdata$LC3Enlarged)])/length(which(Countdata$type==t & Countdata$BvsS==bs & Countdata$LC3Enlarged))
  
  Countdata$PercEnlargedAve[which(Countdata$type==t & Countdata$BvsS==bs)]<-sum(Countdata$PercEnlarged[which(Countdata$type==t & Countdata$BvsS==bs & Countdata$PercEnlarged)])/length(which(Countdata$type==t & Countdata$BvsS==bs & Countdata$PercEnlarged))
  
   Countdata$AveVolEnlargedAve[which(Countdata$type==t & Countdata$BvsS==bs)]<-sum(Countdata$AveVolEnlarged[which(Countdata$type==t & Countdata$BvsS==bs & Countdata$AveVolEnlarged)])/length(which(Countdata$type==t & Countdata$BvsS==bs & Countdata$AveVolEnlarged))
 
   }
}


```

Calculate standard deviation for each condition
```{r}
Countdata$PunctaTotSD<-NA
Countdata$LC3EnlargedSD<-NA
Countdata$PercEnlargedSD<-NA
Countdata$AveVolEnlargedSD<-NA

for (t in c("WT", "Control", "tepsin", "AP4E1")) {
  for (bs in c("Basal", "Starved")) {
  
  Countdata$PunctaTotSD[which(Countdata$type==t & Countdata$BvsS==bs)]<-sd(Countdata$PunctaTot[which(Countdata$type==t & Countdata$BvsS==bs & Countdata$PunctaTot)])
  
  Countdata$LC3EnlargedSD[which(Countdata$type==t & Countdata$BvsS==bs)]<-sd(Countdata$LC3Enlarged[which(Countdata$type==t & Countdata$BvsS==bs & Countdata$LC3Enlarged)])
  
  Countdata$PercEnlargedSD[which(Countdata$type==t & Countdata$BvsS==bs)]<-sd(Countdata$PercEnlarged[which(Countdata$type==t & Countdata$BvsS==bs & Countdata$PercEnlarged)])
  
   Countdata$AveVolEnlargedSD[which(Countdata$type==t & Countdata$BvsS==bs)]<-sd(Countdata$AveVolEnlarged[which(Countdata$type==t & Countdata$BvsS==bs & Countdata$AveVolEnlarged)])
  
  
   }
}
```

Remove duplicate rows from replicates
```{r}
Countdata_nodup<-Countdata[!duplicated(Countdata$PunctaTotAve),]
```


