---
title: "16-Load-Seg-Ind-Puncta-Data"
output: html_notebook
---
CSV import
*change input file path*
```{r}
testdata=read.csv(file="~/Desktop/21Jan21_analysis/NSW3010_Basal_Vol-Int_20Jan21.csv",header=TRUE)
testdata$BvsS<-"Basal"
testdata$Rep<-1
testdata$ImageID<-NA
nobs=nrow(testdata)
for (i in 1:nobs) {
  if (testdata[i,1]=="") {
    testdata[i,1]<-fname
    testdata[i,testdata$ImageID]=substr(temp[i,1],92,94)

  } 
  else {
    fname=testdata[i,1]
    testdata[i,testdata$ImageID]=substr(temp[i,1],92,94)
  }
}

testdata2=read.csv(file="~/Desktop/21Jan21_analysis/NSW3010_Starved_Vol-Int_20Jan21.csv",header=TRUE)
testdata2$BvsS<-"Starved"
testdata2$Rep<-1
nobs=nrow(testdata2)
for (i in 1:nobs) {
  if (testdata2[i,1]=="") {
    testdata2[i,1]<-fname

  } 
  else {
    fname=testdata2[i,1]

  }
}

temp<-rbind(testdata,testdata2)
```

Adding type designation and Image numbers
*if necessary update substring values based on filename in input document*

```{r}
temp$Type<-NA
ntemp<-nrow(temp)


for (c in 1:ntemp) {
  if (substr(temp[c,1],49,49)=="W") {
    temp$Type[c]<-"WT"
  }
  else if (substr(temp[c,1],49,49)=="C") {
    temp$Type[c]<-"Control"
  }
  else if (substr(temp[c,1],49,49)=="t") {
    temp$Type[c]<-"tepsin"
  }
  else {
    temp$Type[c]<-"AP4E1"
  }
  
}
temp$Type<-factor(temp$Type, levels=c("WT", "Control", "tepsin", "AP4E1"))
```

```{r}
temp$Type<-NA
ntemp<-nrow(temp)
temp$ImageID<-NA

temp$BvsS<-factor(temp$BvsS, levels=c("Basal", "Starved"))

for (c in 1:ntemp) {
  for (t in c("WT", "Control", "tepsin", "AP4E1")) {
   for (bs in c("Basal", "Starved")) {
      if (substr(temp[c,1],49,49)=="W" & bs=="Basal") {
    temp$ImageID[c]<-substr(temp[c,1],89,91)
  }
  else if (substr(temp[c,1],49,49)=="C") {
    temp$Type[c]<-"Control"
    temp$ImageID[c]<-substr(temp[c,1],94,96)
  }
  else if (substr(temp[c,1],49,49)=="t") {
    temp$Type[c]<-"tepsin"
    temp$ImageID[c]<-substr(temp[c,1],93,95)
  }
  else {
    temp$Type[c]<-"AP4E1"
    temp$ImageID[c]<-substr(temp[c,1],92,94)
  }
  
   }
  }
}
```


Making Image numbers as factors
```{r}
temp$ImageID<-NA

temp$BvsS<-factor(temp$BvsS, levels=c("Basal", "Starved"))


for (s in temp$Filename) {
  
  temp$ImageID[]=substr(s,92,94)
}

```



Averaging Volumes per Cell
```{r}
temp$AvePuncVolPerCell<-NA

temp$BvsS<-factor(temp$BvsS, levels=c("Basal", "Starved"))

temp$LC3CellID<-as.factor(temp$LC3CellID)

for (t in c("WT", "Control", "tepsin", "AP4E1")) {
  for (bs in c("Basal", "Starved")) {
    for (id in levels(temp$LC3CellID)) {
    temp$AvePuncVolPerCell[which(temp$Type==t & temp$BvsS==bs & temp$LC3CellID==id)]<-sum(temp$LC3PunctaVol[which(temp$Type==t & temp$BvsS==bs & temp$LC3CellID==id)])/length(which(temp$Type==t & temp$BvsS==bs & temp$LC3CellID==id))
  }
}
  }
```

