---
title: "21-Graph-Individual-Puncta-Data"
output: html_notebook
---

density ridges
*CHANGE OUTPUT FILE NAME AND SAVE LOCATION*
```{r}
library(ggplot2)
library(viridis)
library(ggridges)
#temp<-temp[which(temp$Type!="Mock"),]
#temp2<-temp[which(!is.na(temp$ObjectId3D)),]
plotme<-function(dataset,yaxis,labelme,mytitle,nameme){
  ggplot(dataset,aes(x=yaxis,fill=Type, y=Type,group=Type))+
  geom_density_ridges(aes(color=Type) ,alpha=.5,scale=.5,jittered_points=TRUE,position="raincloud",scale=.2,point_size=.5) +
    facet_wrap(~BvsS)+
  xlab(labelme)+
  ggtitle(mytitle)+
  theme()+
  #scale_x_continuous(name=labelme,limits = c(0.6,1))+
    #scale_color_manual(values=c("#EB7D5B", "#FED23F", "#B5D33D","#6CA2EA","#442288"))+
    #scale_fill_manual(values=c("#EB7D5B", "#FED23F", "#B5D33D","#6CA2EA","#442288"))
    scale_fill_viridis(discrete=TRUE,end=.9) +
    scale_color_viridis(discrete=TRUE,end=.9) +
    theme_minimal()+
    theme(plot.title=element_text(hjust=.5), panel.spacing.x = unit(4, "lines"))
}
#tiff(file="~/Desktop/23Jul20_MOC_results/batch-graphs/LC3meanInt_21Feb20-dataset_23Jul20.tiff",width=2800,height=2800,res=600)
plotme(temp,temp$LC3MeanObjIntensity,"puncta mean intensity (A.U.)","LC3 Puncta Mean Intensity")
#dev.off()

#tiff(file="~/Desktop/23Jul20_MOC_results/batch-graphs/LC3punctaVol_21Feb20-dataset_zoom2-10_23Jul20.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$LC3Volume,expression("LC3 Puncta Volume (um"^'3'*")"),"LC3 Puncta Volumes")
#dev.off()

#tiff(file="~/Desktop/23Jul20_MOC_results/batch-graphs/LAMP1Vol_21Feb20-dataset_23Jul20.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$LAMP1Volume,expression("LAMP1 Puncta Volume (um"^'3'*")"),"LAMP1 Puncta Volumes")
#dev.off()

#tiff(file="~/Desktop/23Jul20_MOC_results/batch-graphs/LAMP1meanInt_21Feb20-dataset_23Jul20.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$LAMP1MeanObjIntensity,"puncta mean intensity (A.U.)","LAMP1 Puncta Mean Intensity")
#dev.off()

#tiff(file="~/Desktop/23Jul20_MOC_results/batch-graphs/MOCvalues_21Feb20-dataset_23Jul20.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$MandersLC3MOC,"MOC (A.U.)","LC3/LAMP1 colocalization")
#dev.off()
```

```{r Boxplot}
temp$Type<-factor(temp$Type, levels=c("WT", "Control", "tepsin", "AP4E1"))
library(ggplot2)
library(viridis)
plotme<-function(yaxis,labelme,mytitle,nameme){
#  tiff(file=nameme,width=2800,height=2800,res=600)
  ggplot(temp,aes(x=Type,y=yaxis,fill=BvsS))+
  geom_dotplot(binaxis='y', stackdir='center', stackratio= 0.8, dotsize = 0.25,
    position = position_dodge(0.9),alpha=.5)+
    geom_boxplot(width=.5,position = position_dodge(0.9),alpha=.5, outlier.shape = NA) +
  ylab(labelme)+
  ggtitle(mytitle)+
  theme_minimal()+
  theme(plot.title=element_text(hjust=.5))+
    #scale_y_continuous(name=labelme,limits = c(4000,10000))+
    scale_fill_viridis(discrete=TRUE,begin=.2,end=.8) +
    scale_color_viridis(discrete=TRUE,begin=.2,end=.8)
#  dev.off()
}

#tiff(file="~/Desktop/Analyzed-data_HeLa-KD_7May20/batch-graphs/15mar20_TotVolPerCell.tiff",width=2800,height=2800,res=600)
plotme(temp$MandersLC3MOC,expression("Manders' Overlap Coefficient"),"LC3/LAMP1 colocalization")
#dev.off()

```

Violin plots of individual puncta values

```{r}
plotme<-function(yaxis,labelme,mytitle,nameme){
  ggplot(temp,aes(x=Type,y=yaxis,fill=BvsS))+
  geom_violin(width=.2,position = position_dodge(0.9)) +
  ylab(labelme)+
  ggtitle(mytitle)+
  theme(plot.title=element_text(hjust=.5))
}
#tiff(file="~/Desktop/Analyzed-data/11Mar20_individualPuncta.tiff",width=2800,height=2800,res=600)
plotme(temp$MeanObjIntensity,expression("Puncta Volume (um"^'3'*")"),"Puncta Volumes")
#dev.off()
```
