---
title: "R Notebook"
output: html_notebook
---

boxplots- Mac save file pathing
*filepathing is written for Mac*
```{r}
temp$Type<-factor(temp$Type, levels=c("WT", "Control", "tepsin", "AP4E1"))
temp$BvsS<-factor(temp$BvsS, levels=c("Basal", "Starved"))
library(ggplot2)
# install.packages("remotes")
remotes::install_github("coolbutuseless/ggpattern")
library(ggpattern)
library(viridis)

plotme<-function(dat,yaxis,labelme,mytitle){
   ggplot(dat,aes(x=Type,y=yaxis,fill=Type, pattern=BvsS)) + 
      #geom_boxplot(width=.7,position = position_dodge(0.9),alpha=0.5, outlier.shape = 20, outlier.size = -1) +
    #geom_jitter(position = position_jitterdodge(1.4),alpha=.6, color = "grey") +
    facet_wrap(~BvsS)+
    geom_jitter(position = position_jitterdodge(1.4),alpha=0.8, color= "dark grey") +
    stat_boxplot(geom = "errorbar", width = 0.4) +
    geom_boxplot_pattern(
    aes(),width=0.7,position = position_dodge(0.9),outlier.shape=NA, alpha=0.5,
            pattern_spacing = 0.025,
            pattern_fill = "black",
            pattern_angle = 25,
            pattern_density = 0.1,) + 
    
        guides(pattern = guide_legend(override.aes = list(fill = "white")),
        fill = guide_legend(override.aes = list(pattern = "none")))+
     ylab(labelme)+
     ggtitle(mytitle)+
     theme_minimal()+
     #scale_y_continuous(name=labelme,limits = c(0,175))+
     theme(plot.title=element_text(hjust=.5))+
        scale_fill_viridis(discrete=TRUE,end=.9) +
        scale_color_viridis(discrete=TRUE,end=.9)+
        scale_pattern_manual(values = c(Basal = "none", Starved = "stripe"))
  
}

#tiff(file="~/Desktop/EqCellSum_22Feb21/Final/graphs/LC3PunctaCounts_boxplot_EqCell_016_4Mar21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$LC3PunctaCount, "Number of LC3 positive puncta per cell","Number of LC3 Puncta")
#dev.off()

#tiff(file="~/Desktop/21Jan21_analysis/final/graphs/LC3PunctaVol_boxplot_rep3_16Feb21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLC3VolPerCell, expression("LC3 Puncta Volume (um"^'3'*")"),"Rep 3: Average Volume of LC3 Puncta")
#dev.off()

#tiff(file="~/Desktop/21Jan21_analysis/final/graphs/AveLC3Int_boxplot_rep3_16Feb21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLC3IntPerCell, "Average LC3 puncta intensity (A.U.)","Rep 3: Average LC3 Puncta Intensity")
#dev.off()

#tiff(file="~/Desktop/21Jan21_analysis/final/graphs/AveLC3SumInt_boxplot_rep3_16Feb21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLC3SumIntPerCell, "Average  LC3 puncta sum intensity (A.U.)","Rep 3: Average LC3 Puncta Sum Intensity")
#dev.off()

#tiff(file="~/Desktop/21Jan21_analysis/final/graphs/TotLC3Int_boxplot_zoom_rep3_16Feb21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$TotLC3IntPerCell, "Total LC3 puncta intensity (A.U.)","Rep 3: LC3 Puncta Sum Intensity per Cell")
#dev.off()

#tiff(file="~/Desktop/21Jan21_analysis/final/graphs/LAMPVol_boxplot_rep3_16Feb21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLAMPVolPerCell, expression("LAMP1 Volume (um"^'3'*")"),"Rep 3: Average Volume of LAMP1 Puncta")
#dev.off()

#tiff(file="~/Desktop/21Jan21_analysis/final/graphs/AveLAMPInt_boxplot_rep3_16Feb21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLAMPIntPerCell, "Average LAMP1 puncta intensity (A.U.)","Rep 3: Average LAMP1 Puncta Intensity")
#dev.off()

#tiff(file="~/Desktop/21Jan21_analysis/final/graphs/AveLampSumInt_boxplot_rep3_16Feb21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLAMPSumIntPerCell, "Average LAMP1 puncta sum intensity (A.U.)","Rep 3: Average LAMP1 Puncta Sum Intensity")
#dev.off()

#tiff(file="~/Desktop/21Jan21_analysis/final/graphs/TotLAMPInt_boxplot_rep3_16Feb21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$TotLAMPIntPerCell, "Total LAMP1 puncta intensity (A.U.)","Rep 3: LAMP1 Sum Intensity per Cell")
#dev.off()
```


boxplots- Windows save file pathing
*filepathing is written for Windows*
```{r}
temp$Type<-factor(temp$Type, levels=c("WT", "Control", "tepsin", "AP4E1"))
temp$BvsS<-factor(temp$BvsS, levels=c("Basal", "Starved"))
library(ggplot2)
# install.packages("remotes")
remotes::install_github("coolbutuseless/ggpattern")
library(ggpattern)
library(viridis)

plotme<-function(dat,yaxis,labelme,mytitle){
   ggplot(dat,aes(x=Type,y=yaxis,fill=Type, pattern=BvsS)) + 
      #geom_boxplot(width=.7,position = position_dodge(0.9),alpha=0.5, outlier.shape = 20, outlier.size = -1) +
    #geom_jitter(position = position_jitterdodge(1.4),alpha=.6, color = "grey") +
    facet_wrap(~BvsS)+
    geom_jitter(position = position_jitterdodge(1.4),alpha=0.8, color= "dark grey") +
    stat_boxplot(geom = "errorbar", width = 0.4) +
    geom_boxplot_pattern(
    aes(),width=0.7,position = position_dodge(0.9),outlier.shape=NA, alpha=0.5,
            pattern_spacing = 0.025,
            pattern_fill = "black",
            pattern_angle = 25,
            pattern_density = 0.1,) + 
    
        guides(pattern = guide_legend(override.aes = list(fill = "white")),
        fill = guide_legend(override.aes = list(pattern = "none")))+
     ylab(labelme)+
     ggtitle(mytitle)+
     theme_minimal()+
     #scale_y_continuous(name=labelme,limits = c(0,125000000))+
     theme(plot.title=element_text(hjust=.5))+
        scale_fill_viridis(discrete=TRUE,end=.9) +
        scale_color_viridis(discrete=TRUE,end=.9)+
        scale_pattern_manual(values = c(Basal = "none", Starved = "stripe"))
  
}

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/data-norm/LC3PunctaCounts_boxplot_all-raw_24May21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$LC3PunctaCount, "Number of LC3 positive puncta per cell","Raw-all: Number of LC3 Puncta")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/data-norm/LC3PunctaCounts_boxplot_all-MM_24May21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$LC3CountMinMax, "Number of LC3 positive puncta per cell","Min Max-all: Number of LC3 Puncta")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/data-norm/LC3PunctaCounts_boxplot_all-RS_24May21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$LC3CountRS, "Number of LC3 positive puncta per cell","Robust Scalar-all: Number of LC3 Puncta")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/LC3PunctaVol_boxplot_combined_adj-scale_24Mar21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLC3VolPerCell, expression("LC3 Puncta Volume (um"^'3'*")"),"Average Volume of LC3 Puncta")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/LC3PunctaVol_boxplot_combined_adj-scale_24Mar21.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$LC3VolMinMax, expression("LC3 Puncta Volume (um"^'3'*")"),"Min/Max: Average Volume of LC3 Puncta")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/AveLC3Int_boxplot_combined_24Mar21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLC3IntPerCell, "Average LC3 puncta intensity (A.U.)","Average LC3 Puncta Intensity")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/AveLC3Int_boxplot_combined_24Mar21.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$LC3IntMinMax, "Average LC3 puncta intensity (A.U.)","Min/Max: Average LC3 Puncta Intensity")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/AveLC3SumInt_boxplot_combined_adj-scale_24Mar21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLC3SumIntPerCell, "Average  LC3 puncta sum intensity (A.U.)","Rep 1: Average LC3 Puncta Sum Intensity")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/AveLC3SumInt_boxplot_combined_adj-scale_24Mar21.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$LC3SumIntMinMax, "Average  LC3 puncta sum intensity (A.U.)","Min/Max: Average LC3 Puncta Sum Intensity")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/TotLC3Int_boxplot_combined_adj-scale_24Mar21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$TotLC3IntPerCell, "Total LC3 puncta intensity (A.U.)","LC3 Puncta Sum Intensity per Cell")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/TotLC3Int_boxplot_combined_adj-scale_24Mar21.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$LC3totIntMinMax, "Total LC3 puncta intensity (A.U.)","Min/Max: LC3 Puncta Sum Intensity per Cell")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/LAMPVol_boxplot_combined_24Mar21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLAMPVolPerCell, expression("LAMP1 Volume (um"^'3'*")"),"Average Volume of LAMP1 Puncta")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/LAMPVol_boxplot_combined_24Mar21.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$LAMPVolMinMax, expression("LAMP1 Volume (um"^'3'*")"),"Min/Max: Average Volume of LAMP1 Puncta")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/AveLAMPInt_boxplot_combined_24Mar21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLAMPIntPerCell, "Average LAMP1 puncta intensity (A.U.)","Rep 3: Average LAMP1 Puncta Intensity")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/AveLAMPInt_boxplot_combined_24Mar21.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$LAMPIntMinMax, "Average LAMP1 puncta intensity (A.U.)","Min/Max:  Average LAMP1 Puncta Intensity")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/AveLAMPSumInt_boxplot_combined_24Mar21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$AveLAMPSumIntPerCell, "Average LAMP1 puncta sum intensity (A.U.)","Average LAMP1 Puncta Sum Intensity")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/AveLAMPSumInt_boxplot_combined_24Mar21.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$LAMPSumIntMinMax, "Average LAMP1 puncta sum intensity (A.U.)","Min/Max: Average LAMP1 Puncta Sum Intensity")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/TotLAMPInt_boxplot_combined_adj-scale_24Mar21.tiff",width=3000,height=3000,res=600)
#plotme(temp,temp$TotLAMPIntPerCell, "Total LAMP1 puncta intensity (A.U.)","LAMP1 Sum Intensity per Cell")
#dev.off()

#tiff(file="./Analysis-files/eqCellsum_analysis/graphs/TotLAMPInt_boxplot_combined_adj-scale_24Mar21.tiff",width=3000,height=3000,res=600)
plotme(temp,temp$LAMPtotIntMinMax, "Total LAMP1 puncta intensity (A.U.)","Min/Max: LAMP1 Sum Intensity per Cell")
#dev.off()

```