---
title: "30-Statistical-Analysis"
output: html_notebook
---

ANOVA of all metrics

```{r}
temp$Rep<-as.factor(temp$Rep)

anovaLC3Vol<-aov(temp$AveLC3VolPerCell~temp$Type*temp$BvsS+temp$Rep+temp$Rep:temp$Type)
summary(anovaLC3Vol)
TukeyHSD(anovaLC3Vol)

anovaMeanLC3PuncInt<-aov(temp$AveLC3IntPerCell~temp$Type*temp$BvsS+temp$Rep+temp$Rep:temp$Type)
summary(anovaMeanLC3PuncInt)
TukeyHSD(anovaMeanLC3PuncInt)

anovaSumLC3PuncInt<-aov(temp$AveLC3SumIntPerCell~temp$Type*temp$BvsS+temp$Rep+temp$Rep:temp$Type)
summary(anovaSumLC3PuncInt)
TukeyHSD(anovaSumLC3PuncInt)

anovaTotLC3Int<-aov(temp$TotLC3IntPerCell~temp$Type*temp$BvsS+temp$Rep+temp$Rep:temp$Type)
summary(anovaTotLC3Int)
TukeyHSD(anovaTotLC3Int)

anovaLAMPVol<-aov(temp$AveLAMPVolPerCell~temp$Type*temp$BvsS+temp$Rep+temp$Rep:temp$Type)
summary(anovaLAMPVol)
TukeyHSD(anovaLAMPVol)

anovaMeanLAMPPuncInt<-aov(temp$AveLAMPIntPerCell~temp$Type*temp$BvsS+temp$Rep+temp$Rep:temp$Type)
summary(anovaMeanLAMPPuncInt)
TukeyHSD(anovaMeanLAMPPuncInt)

anovaSumLAMPPuncInt<-aov(temp$AveLAMPSumIntPerCell~temp$Type*temp$BvsS+temp$Rep+temp$Rep:temp$Type)
summary(anovaSumLAMPPuncInt)
TukeyHSD(anovaSumLAMPPuncInt)

anovaTotLAMPInt<-aov(temp$TotLAMPIntPerCell~temp$Type*temp$BvsS+temp$Rep+temp$Rep:temp$Type)
summary(anovaTotLAMPInt)
TukeyHSD(anovaTotLAMPInt)
```

single replicate ANOVA of Individual Puncta Volumes 
*for stats of single replicates*
```{r}
anovaPunctaCount<-aov(temp$LC3PunctaCount~temp$Type*temp$BvsS)
summary(anovaPunctaCount)
TukeyHSD(anovaPunctaCount)

#anovaPunctaLogVol<-aov(temp$LogLC3Volume~temp$Type*temp$BvsS)
#summary(anovaPunctaLogVol)
#TukeyHSD(anovaPunctaLogVol)

#anovaPunctaInt<-aov(temp$LC3MeanObjIntensity~temp$Type*temp$BvsS)
#summary(anovaPunctaInt)
#TukeyHSD(anovaPunctaInt)

#anovaLC3MOC<-aov(temp$MandersLC3MOC~temp$Type*temp$BvsS)
#summary(anovaLC3MOC)
#TukeyHSD(anovaLC3MOC)

#anovaLAMPInt<-aov(temp$LAMP1MeanObjIntensity~temp$Type*temp$BvsS)
#summary(anovaLAMPInt)
#TukeyHSD(anovaLAMPInt)
```